# Generated by Django 4.2.2 on 2023-06-18 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Sure_Name', models.CharField(max_length=50)),
                ('Age', models.PositiveIntegerField()),
                ('Course', models.CharField(max_length=50)),
                ('Musical_Instrument', models.CharField(choices=[('g', 'Гитара'), ('f', 'Фортепиано'), ('b', 'Барабаны'), ('s', 'Скрипка'), ('t', 'Труба'), ('a', 'Аккордеон')], max_length=50)),
                ('Progress', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(12)])),
                ('Payment', models.BooleanField()),
            ],
        ),
    ]
