# Generated by Django 4.2.2 on 2023-06-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Payment',
            field=models.CharField(choices=[('true', 'Заплатил'), ('false', 'Не заплатил')], max_length=50),
        ),
    ]
